#Default Active Profile
spring.profiles.active: local

server:
  servlet.application-display-name: Bank Customer App (${spring.profiles.active})
  port: 9000

spring:
  application.name: bank-customer-app-${spring.profiles.active}
  jackson:
    date-format: yyyy-MM-dd
    serializatipon.indent-output: true
    default-property-inclusion: non_null
  
logging.file:
  name: bank-customer-log.log
  path: /logs
  max-history: 2
  max-size: 5MB
  level:
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
    org.springframework: INFO
    com.example.bank.bankcustomerapp: DEBUG
---
 
#Local Profile
debug: true
spring:
  profile: local
  show-sql: true
  datasource:
    url: jdbc:h2:mem:bank-customer-app-db
    driverClassName: org.h2.Driver
    username: h2admin
    password: password
    platform: h2
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none;
      format_sql: true
      generate_statistics: true  
  h2:
    console.enabled: true
    settings.trace: true